name: build-test-workflow
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: cd frontend
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm install

      - name: cd bakckend
        run: |
          cd backend-ts
          npm install

      - name: Build buckend
        run: |
          cd backend-ts
          npm run build